### PR TITLE
Digonto abundance

### PR DESCRIPTION
**Pull request by Digonto-computer**

### CODE REVIEW

**Comment by Digonto-computer** [comment]
there seems to be a problem with one of the small examples in example

**Comment by orlox** [comment]
It works if you set the abundance to X=1, Y=0 and Z=0. I think the issue is that you are filling in the correct abundances, but you are not using that abundance for the EOS or the opacity. This is in your calls to `getlnT_NewtonRhapson` and `get_opacity_resultsTρ`, where you use X=1,Y=0 as the abundance. This will make the initial condition crappy, so we don't find a solution and the solver crashes.

**Comment by orlox** [comment]
also a quick comment, you do not need to make a call to `massfractions = get_mass_fractions(abundanceList, sm.network, X, Z, Dfraction)`  at every cell. You can do this at the very beginning and then use those wherever they're needed.

**Comment by Digonto-computer** [comment]
so I now did it with X=1, Y=0. But probably I should remove the hardcoded X=1, Y=0 abundances in `getlnT_NewtonRhapson` and `get_opacity_resultsTρ`.

**Comment by Digonto-computer** [comment]
so I now removed the X=1.0, Y=0.0 hardcode by changing some functions.

**Comment by orlox** [comment]
Another quick comment, in your `get_mass_fractions` function you don't really need to receive the nuclear network, just `network.species_names`.

**Comment by orlox** [comment]
Noticed a couple of issues already, will commit something in a bit

**Comment by orlox** [comment]
I think this is good now, although I had to switch to a 0.5Msun star. Seems the addition of CNO leads to a meaningful contribution of the CNO cycle, a brighter star, and convergence issues. We should however merge #77 first

**Pull request merged**
