### PR TITLE
Deprecate-ssi

### PR DESCRIPTION
**Pull request by matthiasfabry**
This removes the `StellarStepInfo` `struct` in favor of the new `StellarModelProperties`. Values from within can be accessed using:
```
get_cell_value(sm.props.lnT[sm.props.nz])
```
Also includes some minor doc changes

### CODE REVIEW

**Comment by orlox** [comment]
This is looking good, though I think its good to double check we're on the same page here, as dealing with state is a pain point in MESA and would be good to have it clear in one go. One quick thing I noticed already is that this will potentially break retries. With this setup we only carry one copy of ind_vars, while before with the step info we also copied that. This allowed us to go back to those values if the step did not work. I would suggest moving ind_vars to also be part of StellarModelProperties, though this will need some extra bits to copy ind_vars when cycling.

If we do this, we might want to remove `dm`, `m`, `nz` from StellarModel, as they only replicate information. That would remove most specific details out of StellarModel, and leave StellarModel covering just the basic physics that define the model. It could also make it easier to define a one-zone model for Eva's work, in that case we can define a simple StellarModelProperties that does not include irrelevant info such as radius or temperature gradients.

**Comment by matthiasfabry** [comment]
Completely agree, lemme get on it!

**Comment by matthiasfabry** [comment]
I believe this is it. It's a lot of changes, but necessary IMHO to adopt early rather than later. Otherwise many conflicts will need to be addressed down the line (_e.g.,_ all `sm.nz` become `sm.props.nz` now, _etc..._)

**Comment by matthiasfabry** [comment]
as the commit says. We were still reading `sm.props.nz` in the InitialCondition creator. Instead, `nz` is now a parameter of any `InitialCondition` call, so I made that explicit

**Comment by orlox** [comment]
aok to merge then?

**Comment by matthiasfabry** [comment]
if you all agree, please go ahead!

**Comment by orlox** [comment]
You're probably missing an LSUN factor in the output, as the HR reports the luminosity to be logL/Lsun~-33. Other than that it all looks good, feel free to merge.

**Pull request merged**
